---

- name: Download wp-cli
  get_url: url=https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp

- name: Set permissions for wp-cli
  file: path=/usr/local/bin/wp owner=root group=root mode=0755
